services:
  - type: web
    name: mycarprediction
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0